### PR TITLE
feat(common_awsim_labs_sensor_launch): distortion corrector add new param

### PR DESCRIPTION
**Pull request by vividf**
## Description

- https://github.com/autowarefoundation/autoware.universe/pull/8380
add a new parameter for distortion correction node, thus common sensor launch also needs to update the parameter

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by vividf** [comment]
@xmfcx could you reveiw this, thanks!

**Review by xmfcx — APPROVED** [review]
👍✨

**Comment by vividf** [comment]
@xmfcx seems that pre-commit failed on this repository

**Comment by xmfcx** [comment]
Sorry it's this one:
- https://github.com/autowarefoundation/autoware.universe/pull/8380

I've approved this.

First universe PR should be merged.
Then we can merge these.

**Comment by vividf** [comment]
@xmfcx Universe's PR is merged so we can merge this one :)

**Pull request merged**
