### PR TITLE
chore: changed the package name imu_corrector to autoware_imu_corrector

### PR DESCRIPTION
**Pull request by knzo25**
## Description
Launcher counterpart of https://github.com/autowarefoundation/autoware.universe/pull/8222

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@xmfcx @mitsudome-r 
Could you review or assign reviewers? (I am mentioning you guys since you have approved PRs here in the past)

**Comment by knzo25** [comment]
@xmfcx @mitsudome-r 
Friendly ping

**Comment by knzo25** [comment]
@xmfcx @mitsudome-r 
The parent PR was merged since there were no replies here

**Review by xmfcx — APPROVED** [review]
Thank you, sorry for the delay 🙇‍♂️

**Pull request merged**
